"use client"
import { useState } from "react"
import Navbar from '@/components/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'

import './globals.css'
import React from 'react'
import { Provider } from "react-redux"
import store from "@/store/store"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body >
      <Provider store={store}>
        <Navbar  />
        <div className="w-full flex " style={{alignItems: 'stretch'}}>
        <Sidebar  />
        {children}
      
        </div>
      </Provider>
      </body>
    </html>
  )
}
